<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<jsp:include page="/_admin/_header.jsp"/>
            
            <section id="admin-index">
                <nav>
                    <h3>관리자 메인</h3>
                    <p>
                        HOME > <strong>메인</strong>
                    </p>
                </nav>
                <h4>쇼핑몰 운영현황</h4>
                <article>
                    <table>
                        <tbody>
                            <tr>
                                <td>
                                    <strong>주무건수(건)</strong>
                                    <span>131</span>
                                </td>
                                <td>
                                    <strong>주무건수(건)</strong>
                                    <span>131</span>
                                </td>
                                <td>
                                    <strong>주무건수(건)</strong>
                                    <span>131</span>
                                </td>
                                <td>
                                    <strong>주무건수(건)</strong>
                                    <span>131</span>
                                </td>
                                <td>
                                    <strong>주무건수(건)</strong>
                                    <span>131</span>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <p>
                                        <span>PC</span>
                                        <span>60</span>
                                    </p>
                                    <p>
                                        <span>Mobile</span>
                                        <span>60</span>
                                    </p>
                                </td>
                                <td>
                                    <p>
                                        <span>PC</span>
                                        <span>60</span>
                                    </p>
                                    <p>
                                        <span>Mobile</span>
                                        <span>60</span>
                                    </p>
                                </td>
                                <td>
                                    <p>
                                        <span>PC</span>
                                        <span>60</span>
                                    </p>
                                    <p>
                                        <span>Mobile</span>
                                        <span>60</span>
                                    </p>
                                </td>
                                <td>
                                    <p>
                                        <span>PC</span>
                                        <span>60</span>
                                    </p>
                                    <p>
                                        <span>Mobile</span>
                                        <span>60</span>
                                    </p>
                                </td>
                                <td>
                                    <p>
                                        <span>PC</span>
                                        <span>60</span>
                                    </p>
                                    <p>
                                        <span>Mobile</span>
                                        <span>60</span>
                                    </p>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <p>
                                        <span>어제</span>
                                        <span>4</span>
                                    </p>
                                    <p>
                                        <span>주간</span>
                                        <span>10</span>
                                    </p>
                                    <p>
                                        <span>월간</span>
                                        <span>30</span>
                                    </p>
                                </td>
                                <td>
                                    <p>
                                        <span>어제</span>
                                        <span>4</span>
                                    </p>
                                    <p>
                                        <span>주간</span>
                                        <span>10</span>
                                    </p>
                                    <p>
                                        <span>월간</span>
                                        <span>30</span>
                                    </p>
                                </td>
                                <td>
                                    <p>
                                        <span>어제</span>
                                        <span>4</span>
                                    </p>
                                    <p>
                                        <span>주간</span>
                                        <span>10</span>
                                    </p>
                                    <p>
                                        <span>월간</span>
                                        <span>30</span>
                                    </p>
                                </td>
                                <td>
                                    <p>
                                        <span>어제</span>
                                        <span>4</span>
                                    </p>
                                    <p>
                                        <span>주간</span>
                                        <span>10</span>
                                    </p>
                                    <p>
                                        <span>월간</span>
                                        <span>30</span>
                                    </p>
                                </td>
                                <td>
                                    <p>
                                        <span>어제</span>
                                        <span>4</span>
                                    </p>
                                    <p>
                                        <span>주간</span>
                                        <span>10</span>
                                    </p>
                                    <p>
                                        <span>월간</span>
                                        <span>30</span>
                                    </p>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </article>
                <h4>주문 업무현황</h4>
                <article>
                    <table>
                        <tbody>
                            <tr>
                                <td>
                                    <strong>입금대기(건)</strong>
                                    <span>100</span>
                                </td>
                                <td>
                                    <strong>입금대기(건)</strong>
                                    <span>100</span>
                                </td>
                                <td>
                                    <strong>입금대기(건)</strong>
                                    <span>100</span>
                                </td>
                                <td>
                                    <strong>입금대기(건)</strong>
                                    <span>100</span>
                                </td>
                                <td>
                                    <strong>입금대기(건)</strong>
                                    <span>100</span>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </article>
                <div>
                    <div>
                        <h4>공지사항</h4>
                         <article>
                            <table>
                            <c:forEach items="${notice}" var="article">
                            	<tr class="index_notice">
	                                <td><a href="/Kmarket/admin/cs/notice/view.do?no=${article.no}&cate=전체보기&pg=1">${article.title}</a></td>
	                                <td align="right">${article.rdate}</td>
	                            </tr>
                            </c:forEach>
                            </table>
                        </article>
                    </div>
                    <div>
                        <h4>고객문의</h4>
                        <article>
                        	<table>
                        	<c:forEach items="${qna}" var="article">
                        		<tr class="index_notice">
	                                <td><a href="/Kmarket/admin/cs/qna/view.do?no=${article.no}">[${article.cate}] ${article.title}</a></td>
	                                <td align="right">${article.rdate}</td>
	                            </tr>
                        	</c:forEach>
                            </table>
                        </article>
                    </div> 
                </div>
            </section>
        </main>
<jsp:include page="/_admin/_footer.jsp"/>
        